export const basicsCourseModules = [
  { href: "/current-voltage-learning/1", title: "Lesson 1 Current and Voltage" },
  { href: "/measurement-practical-basics/1", title: "Lesson 2 Measurement Practical Basics" },
  { href: "/resistor-learning", title: "Lesson 3 Resistor Learning" },
  { href: "/capacitor-learning/1", title: "Lesson 4 Capacitor Learning" },
  { href: "/diode-learning/1", title: "Lesson 5 Diode Learning" },
  { href: "/transformer-learning/1", title: "Lesson 6 Transformer Learning" },
  { href: "/fuse-learning/1", title: "Lesson 7 Fuse Learning" },
  { href: "/magnetic-contactor-learning", title: "Lesson 8 Magnetic Contactor Learning" },
  { href: "/optocoupler-learning/1", title: "Lesson 9 Optocoupler Learning" },
  { href: "/pushbutton-learning/1", title: "Lesson 10 Pushbutton Learning" },
  { href: "/relay-learning/1", title: "Lesson 11 Relay Learning" },
  { href: "/transistor-learning/1", title: "Lesson 12 Transistor Learning" },
  { href: "/voltage-regulator-learning/1", title: "Lesson 13 Voltage Regulator Learning" },
  { href: "/water-flow-analogy", title: "Lesson 14 Water Flow Analogy" },
];

export const basicsCourseProjects = [
  {
    href: "/dol-project",
    title: "Step 1 DOL Starter Project",
    shortTitle: "DOL Starter Project",
    description: "Start with the direct-on-line motor starter sequence and understand the basic power and control flow.",
    status: "ready" as const,
  },
  {
    href: "/linear-power-supply-project",
    title: "Step 2 Linear Power Supply Project",
    shortTitle: "Linear Power Supply Project",
    description: "Follow AC input, transformer, rectifier, filter capacitor, and regulator behavior in one guided build.",
    status: "ready" as const,
  },
  {
    href: "/reverse-forward-project",
    title: "Step 3 Reverse Forward Project",
    shortTitle: "Reverse Forward Project",
    description: "Practice forward and reverse motor control with interlock logic in a step-by-step industrial sequence.",
    status: "ready" as const,
  },
  {
    href: "/mosfet-p-channel-switch-circuit-project",
    title: "Step 4 MOSFET P-Channel Switch Project",
    shortTitle: "MOSFET P-Channel Switch",
    description: "Learn high-side switching behavior and gate control using a P-channel MOSFET workspace.",
    status: "ready" as const,
  },
  {
    href: "/mosfet-n-channel-switch-circuit-project",
    title: "Step 5 MOSFET N-Channel Switch Project",
    shortTitle: "MOSFET N-Channel Switch",
    description: "Practice N-channel switching behavior with the corrected workspace and live simulation route.",
    status: "ready" as const,
  },
  {
    href: "/npn-transistor-switching-project",
    title: "Step 6 NPN Transistor Switching Project",
    shortTitle: "NPN Transistor Switching",
    description: "Build the low-side transistor switching flow and see how the NPN device controls the load path.",
    status: "ready" as const,
  },
  {
    href: "/pnp-transistor-switching-project",
    title: "Step 7 PNP Transistor Switching Project",
    shortTitle: "PNP Transistor Switching",
    description: "Compare the PNP control path with the NPN project and understand the reversed current direction.",
    status: "ready" as const,
  },
  {
    href: "/star-delta-with-timer",
    title: "Step 8 Star Delta With Timer",
    shortTitle: "Star Delta With Timer",
    description: "Run the advanced motor-starting sequence with star, transfer, and delta stages in one workspace.",
    status: "ready" as const,
  },
  {
    href: "/led-with-resistor-project",
    title: "Step 9 LED With Resistor",
    shortTitle: "LED With Resistor",
    description: "Placeholder scaffold for a dedicated beginner LED and resistor mini-project route.",
    status: "coming-soon" as const,
  },
  {
    href: "/bridge-rectifier-power-supply-project",
    title: "Step 10 Bridge Rectifier Power Supply",
    shortTitle: "Bridge Rectifier Power Supply",
    description: "Placeholder scaffold for a beginner bridge rectifier power supply mini-project route.",
    status: "coming-soon" as const,
  },
  {
    href: "/regulated-dc-supply-project",
    title: "Step 11 Regulated DC Supply",
    shortTitle: "Regulated DC Supply",
    description: "Placeholder scaffold for a simplified regulated DC supply mini-project route.",
    status: "coming-soon" as const,
  },
  {
    href: "/ldr-automatic-light-project",
    title: "Step 12 LDR Automatic Light",
    shortTitle: "LDR Automatic Light",
    description: "Placeholder scaffold for an LDR automatic light mini-project route.",
    status: "coming-soon" as const,
  },
  {
    href: "/thermistor-temperature-alarm-project",
    title: "Step 13 Thermistor Temperature Alarm",
    shortTitle: "Thermistor Temperature Alarm",
    description: "Placeholder scaffold for a thermistor temperature alarm mini-project route.",
    status: "coming-soon" as const,
  },
  {
    href: "/transistor-switch-circuit-project",
    title: "Step 14 Transistor Switch Circuit",
    shortTitle: "Transistor Switch Circuit",
    description: "Placeholder scaffold for a simplified transistor switch circuit mini-project route.",
    status: "coming-soon" as const,
  },
  {
    href: "/mosfet-load-switch-project",
    title: "Step 15 MOSFET Load Switch",
    shortTitle: "MOSFET Load Switch",
    description: "Placeholder scaffold for a simplified MOSFET load switch mini-project route.",
    status: "coming-soon" as const,
  },
  {
    href: "/simple-sensor-interface-project",
    title: "Step 16 Simple Sensor Interface",
    shortTitle: "Simple Sensor Interface",
    description: "Placeholder scaffold for a simple sensor interface capstone mini-project route.",
    status: "coming-soon" as const,
  },
];
