"use client";

import type { ResistorType } from "./types";

export const resistorTypes: ResistorType[] = [
  {
    key: "carbon",
    category: "Fixed",
    name: "Carbon Composition Resistor",
    short: "Low-cost general-purpose fixed resistor.",
    valueLabel: "Fixed resistance",
    accuracy: 35,
    power: 45,
    cost: 90,
    response: 55,
    color: "#334155",
    bestFor: "General low-cost electronics",
    limitation: "Higher noise and lower precision.",
    application: "Basic LED circuit, school lab, simple PCB",
  },
  {
    key: "metalFilm",
    category: "Fixed",
    name: "Metal Film Resistor",
    short: "Precise and stable fixed resistor.",
    valueLabel: "High-precision fixed value",
    accuracy: 92,
    power: 55,
    cost: 65,
    response: 75,
    color: "#2563eb",
    bestFor: "Precision signal circuits",
    limitation: "Not ideal for heavy power dissipation.",
    application: "Sensors, amplifiers, measuring circuits",
  },
  {
    key: "wireWound",
    category: "Fixed",
    name: "Wire Wound Resistor",
    short: "High-power resistor made with wound resistance wire.",
    valueLabel: "Fixed high-power value",
    accuracy: 80,
    power: 95,
    cost: 45,
    response: 45,
    color: "#f97316",
    bestFor: "High-power and heat-load circuits",
    limitation: "Larger size and possible inductive effect.",
    application: "Power supplies, heater loads, braking circuits",
  },
  {
    key: "potentiometer",
    category: "Variable",
    name: "Potentiometer",
    short: "Variable resistor controlled by a knob or slider.",
    valueLabel: "Adjustable resistance",
    accuracy: 60,
    power: 50,
    cost: 60,
    response: 80,
    color: "#8b5cf6",
    bestFor: "Manual control",
    limitation: "Mechanical wear over time.",
    application: "Volume control, dimmer, calibration knob",
  },
  {
    key: "thermistor",
    category: "Sensor",
    name: "Thermistor",
    short: "Temperature-sensitive resistor.",
    valueLabel: "Resistance changes with temperature",
    accuracy: 70,
    power: 35,
    cost: 70,
    response: 88,
    color: "#ef4444",
    bestFor: "Temperature sensing",
    limitation: "Non-linear response.",
    application: "Battery protection, thermostats, fan control",
  },
  {
    key: "ldr",
    category: "Sensor",
    name: "Light Dependent Resistor",
    short: "Light-sensitive resistor.",
    valueLabel: "Resistance changes with light",
    accuracy: 50,
    power: 25,
    cost: 80,
    response: 45,
    color: "#eab308",
    bestFor: "Light detection",
    limitation: "Slower response and lower precision.",
    application: "Automatic lights, light sensor modules",
  },
];
